---
name: 'CI'
on:
  push:
    branches:
      - 'main'
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
      - '*'
jobs:
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@master'
        with:
          config_file: '.yamllint'
